version: '4.2'

services:
  web:
    image: django_tutorial
    restart: always
    environment:
      DB_HOST: db
      DB_NAME: tutorial
      DB_USER: tutorial
      DB_PASSWORD: secret

      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_EMAIL: admin@example.com
      DJANGO_SUPERUSER_PASSWORD: admin123
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: tutorial
      MYSQL_USER: tutorial
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
